from quagga.optimizers.policies.FixedMomentumPolicy import FixedMomentumPolicy
from quagga.optimizers.policies.FixedLearningRatePolicy import FixedLearningRatePolicy
from quagga.optimizers.policies.ScheduledLearningRatePolicy import ScheduledLearningRatePolicy
