gpu_matrix_kernels:
	/usr/local/cuda-7.0/bin/nvcc -Xcompiler -fPIC -shared -o gpu_matrix_kernels.so gpu_matrix_kernels.cu
nonlinearities:
	/usr/local/cuda-7.0/bin/nvcc -Xcompiler -fPIC -shared -o nonlinearities.so nonlinearities.cu
test_events:
	/usr/local/cuda-7.0/bin/nvcc -Xcompiler -fPIC -shared -o test_events.so test_events.cu
